<?php 
$this->title = 'Commentaires'; 
?>
<p><button><a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=index');?>">Retour</a></button></p>
<article class="comments">
	<fieldset>
		<legend>Vos commentaires</legend>
		<?php 
		foreach ($data as $key => $value) {?>
			<div class="comment">
				<h4>Auteur : <?= $data[$key]['userPseudo'] ?></h4>
				<p><?= $data[$key]['content'] ?></p>
				<p><em>Posté le : <?= $data[$key]['dateComment'] ?></em></p>
				<form action="<?php echo $this->app->getUrl('?controller=comment&action=save');?>" method="post">
					<p><textarea name="content" id="mytextarea" placeholder="Votre commentaire" rows="5" required="required"></textarea></p>
					<input type="hidden" name="userId" value="1">
					<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
					<input type="hidden" name="articleId" value="<? $this->request->getParam('id') ?>">
					<input type="hidden" name="idParent" value="<? echo $data[$key]['id'] ?>">
					<input type="submit" value="Envoyer">
				</form>
				<?php if (isset($data[$key]['response'])) {
					foreach ($data[$key]['response'] as $comment => $com) {?>
						<div class="sousCommentaire" style="margin-left: 50px">
							<h4>Auteur : <?= $data[$key]['response'][$comment]['userPseudo'] ?></h4>
							<p><?= $data[$key]['response'][$comment]['content'] ?></p>
							<p><em>Posté le : <?= $data[$key]['response'][$comment]['dateComment'] ?></em></p>
						</div>
				<?php }}  ?>
			</div>	
		<?php }?>
		<form action="<?php echo $this->app->getUrl('?controller=comment&action=save');?>" method="post">
			<p><textarea name="content" id="mytextarea" placeholder="Votre commentaire" rows="5" required="required"></textarea></p>
			<input type="hidden" name="userId" value="1">
			<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
			<input type="hidden" name="articleId" value="<? $this->request->getParam('id') ?>">
			<input type="hidden" name="idParent" value="0">
			<input type="submit" value="Envoyer">
		</form>
	</fieldset>
</article>
