<?php 
	$this->title = 'Administration : Biographie'; 
?>

	<div class="auth">
		<form method="post" action="<?php echo $this->app->getUrl('?interface=admin&controller=biography&action=post');?>">
			<fieldset>
				<legend>Veuillez écrire ou modifier votre biographie : </legend>
				<p><textarea name="content" id="tinyMCE1" placeholder="Contenu de votre biographie" rows="15" cols="100"><?php  echo $data[0];?></textarea></p>
				<p><input type="submit" value="Envoyer"></p>
			</fieldset>
		</form>

	</div>
