<?php 
$this->title = 'Mon Blog : Liste des articles'; 
?>
<div class="row">
    <div id="accueil" class="mainImage">
        <img src="web/img/main.jpg" alt="Vue de l\'Alaska" class="img-responsive">
        <div class="textMainImage">
            <h1>Billet simple pour l'Alaska</h1>
            <h4>Par Jean Forteroche</h4>
            <button type="button" class="btn btn-default"><a href="index.php#news">Découvre les derniers chapitres</a></button>
        </div>
    </div>
</div>
<div class="row">
	<section class="container-fluid news" id="news">
		<div class="title"><h1>Derniers chapitres</h1></div>
		<?php foreach ($data as $key => $value){ 
			$overview = substr(strip_tags($data[$key]['content']),0, 80) . '...';
		?>
		<div class="col-sm-4">
			<div class="panel panel-default">
			  <div class="panel-heading"><h3><a href="<?php echo $this->app->getUrl('?controller=article&action=show&id=' . $data[$key]['id']);?>"><?= $data[$key]['title'] ?></a></h3></div>
			  <div class="panel-body">
			  	<figure class="lastArticles">
				  	<img src="web/img/book.jpg" alt="Livre ouvert" class="img-responsive vignetteLivre">
				  	<figcaption>
				  		<p><?= $overview ?></p>
				  		<button class="btn btn-default"><a href="<?php echo $this->app->getUrl('?controller=article&action=show&id=' . $data[$key]['id']);?>"></a>Lire l'article</button>
				  	</figcaption>	
			  	</figure>
			  </div>
			  <div class="panel-footer"><em>Créer le : <?= $data[$key]['dateArticle'] ?></em></div>
			</div>
		</div>
		<?php } ?>
	</section>
</div>
<div class="row">
	<section id="biographie" class="container-fluid biographie">
		<div class="title"><h1>Biographie de l'auteur</h1></div>
			<div class="bio">
				<div class="col-sm-4">
					<img src="web/img/auteur.jpg" alt="" class="img-responsive auteur">
				</div>
				<div class="col-sm-8">
					<div class="panel panel-default">
					  <div class="panel-heading"><h4>Jean Forteroche</h4></div>
					  <div class="panel-body">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					  </div>
					</div>
				</div>
			</div>
	</section>
</div>


