<?php 
$this->title = 'Interface d\'inscription nouvel utilisateur'; 
?>
<div class="row auth">
  <section>
    <fieldset class="col-xs-8 col-xs-offset-2">
        <legend><h2 class="title">Nouvel utilisateur</h2></legend>
        <form class="form-horizontal" action="<?php echo $this->app->getUrl('?controller=user&action=save');?>" method="post">
            <div class="form-group">
              <label class="control-label col-sm-4" for="pseudo">Pseudo :</label>
              <div class="col-sm-8">
                <input class="form-control" type="text" name="pseudo"  id="pseudo" placeholder="Votre pseudo" required="required">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4" for="email">Adresse email:</label>
              <div class="col-sm-8">
                <input class="form-control" type="email" name="email"  id="email" placeholder="Entrer votre adresse email" required="required">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4" for="pass">Mot de passe :</label>
              <div class="col-sm-8"> 
                <input type="password" class="form-control" id="pass" name="pass" required="" placeholder="Entrer votre mot de passe">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4" for="pass2">Confirmer votre mot de passe :</label>
              <div class="col-sm-8"> 
                <input type="password" class="form-control" id="pass2" name="pass2" required="" placeholder="Entrer à nouveau votre mot de passe">
              </div>
            </div>
            <div class="form-group"> 
                <div class="col-sm-8 col-sm-offset-2">
                  <div class="checkbox">
                      <label for="remember"><input type="checkbox" id="remember" name="remember">Se souvenir de moi ?</label>
                  </div>
               </div>
            </div>
            <div class="form-group"> 
              <div class="col-sm-2 col-sm-offset-4">
                  <button type="submit" class="btn btn-default">Inscription</button>
              </div>
              <div class="col-sm-2">
                 <button class="btn btn-danger"><a class="annulation" href="<?php echo $this->app->getUrl('?controller=user&action=registration');?>">Annulation</a></button>
              </div>
            </div>
        </form>
    </fieldset> 
  </section>    
</div>
