<?php
	
    
?>

<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="web/css/style.css">
        <title><?= $title ?></title>
    </head>
    <body>
        <div id="content">
			<h1>Bienvenue sur votre interface d'administration</h1>
            <form action="http://localhost/Projet4/Projet-4-Creez-un-blog-pour-un-ecrivain/?interface=admin&controller=auth&action=logout" method="post">
                <input type="submit" value="logout">
            </form>
            <div id="specificContent">
                <?= $content ?>
            </div>
            <footer>
                <p>Site réalisé par Florian Garcia</p>
            </footer>    
        </div>
        <script type="text/javascript" src="web/js/script.js"></script> 
    </body>
</html>
