<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="web/css/style.css">
        <title><?= $title ?></title>
        <script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
        <script type="text/javascript" src="web/js/tinymce.js"></script> 
    </head>
    <body>
        <div id="content">
			<h1>Bienvenue sur votre interface d'administration</h1>
            <button><a href="index.php?interface=admin&controller=auth&action=logout">Logout</a></button>
            <div id="specificContent">
                <?= $content ?>
            </div>
            <footer>
                <p>Site réalisé par Florian Garcia</p>
            </footer>    
        </div>
        <script type="text/javascript" src="web/js/script.js"></script> 
    </body>
</html>

