<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700|Lora:400,400i,700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="web/css/style.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="web/js/script.js"></script> 
    </head>
    <body>
        <div id="content" class="container-fluid">
            <div class="row">
                <header>
                    <nav class="navbar navbar-default navbar-fixed-top">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span> 
                                </button>
                                <a class="navbar-brand" href="<?php echo $this->app->getUrl('?controller=home&action=index');?>"><i class="glyphicon glyphicon-home"></i> Jean Forteroche</a>
                            </div>
                            <div class="collapse navbar-collapse" id="myNavbar">
                                <ul class="nav navbar-nav navbar-right">
                                    <li><a href="<?php echo $this->app->getUrl('?controller=article&action=index');?>"><i class="glyphicon glyphicon-book"></i> Chapitres</a></li>
                                    <li><a href="<?php echo $this->app->getUrl('?controller=home&action=index#biographie');?>"><i class="glyphicon glyphicon-info-sign"></i> Biographie</a></li> 
                                    <li>
                                        <?php if (isset($_SESSION['pseudo'])) {?>
                                            <a href="<?php echo $this->app->getUrl('?controller=authUser&action=logout');?>"><span class="glyphicon glyphicon-off"></span> Déconnection</a>
                                        <?php }else{?>
                                            <a href="<?php echo $this->app->getUrl('?controller=authUser&action=auth');?>"><span class="glyphicon glyphicon-log-in"></span> Connection</a>
                                    </li>
                                     <li><a href="<?php echo $this->app->getUrl('?controller=user&action=registration');?>"><span class="glyphicon glyphicon-user"></span> Inscription</a></li>
                                        <?php } ?>  
                                </ul>
                            </div>
                        </div>
                    </nav>
                </header>
            </div>
            <div class="row">
                <?php if (!empty($_SESSION['successMessage'])) { ?>
                    <div class="alert alert-success alert-dismissable fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <i class="icon icon-check-circle icon-lg"></i>
                        <strong>Succès !</strong> <?php echo $_SESSION['successMessage'] ?>
                    </div>
                   <?php $_SESSION['successMessage'] = "" ?>
                <?php } ?>
               <?php if (!empty($_SESSION['errorMessage'])) { ?>
                    <div class="alert alert-danger alert-dismissable fade in">       
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <i class="icon icon-times-circle icon-lg"></i>
                        <strong>Erreur !</strong> <?php echo $_SESSION['errorMessage'] ?>.
                    </div>       
                   <?php $_SESSION['errorMessage'] = "" ?>
               <?php } ?> 
            </div>
            <div class="row">
                 <?= $content ?>
            </div>
            <div class="row">
                <footer>
                    <p>Site réalisé par Florian Garcia</p>
                </footer>  
            </div>
        </div>
    </body>
</html>
