<?php 
	$this->title = 'Administration : Identification'; 
?>

	<div class="auth">
		<h2>Bienvenue sur la page d'authentification de la partie administrateur du site</h2>
		<form method="post" action="http://localhost/Projet4/Projet-4-Creez-un-blog-pour-un-ecrivain/?interface=admin&controller=auth&action=login">
			<fieldset>
				<legend>Veuillez entrez vos identifiants : </legend>
				<p><label for="pseudo">Votre pseudo : <input type="text" name="pseudo" id="pseudo"></label></p>
				<p><label for="pseudo">Votre mot de passe : <input type="password" name="pass" id="pass"></label></p>
				<p><input type="submit" value="Envoyer"></p>
			</fieldset>
		</form>

	</div>




