-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 10:53:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog` DEFAULT CHARACTER SET utf8 ;
USE `Blog` ;

-- -----------------------------------------------------
-- Table `Blog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  `email` VARCHAR(255) NULL,
  `pass` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  `email` VARCHAR(255) NULL,
  `pass` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NULL,
  `content` LONGTEXT NULL,
  `dateArticle` DATETIME NULL,
  `adminId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_admin1_idx` (`adminId` ASC),
  CONSTRAINT `fk_article_admin1`
    FOREIGN KEY (`adminId`)
    REFERENCES `Blog`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `article_id` INT NOT NULL,
  INDEX `fk_user_1_article_idx` (`article_id` ASC),
  CONSTRAINT `fk_user_1_article`
    FOREIGN KEY (`article_id`)
    REFERENCES `Blog`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Blog`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NULL,
  `content` LONGTEXT NULL,
  `userId` INT NOT NULL,
  `dateCommentaire` DATETIME NULL,
  `articleId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaires_user1_idx` (`userId` ASC),
  INDEX `fk_commentaires_article1_idx` (`articleId` ASC),
  CONSTRAINT `fk_commentaires_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `Blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_article1`
    FOREIGN KEY (`articleId`)
    REFERENCES `Blog`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`adminReplyCommentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`adminReplyCommentaire` (
  `adminId` INT NOT NULL,
  `commentaireId` INT NOT NULL,
  `content` LONGTEXT NULL,
  `dateReply` DATETIME NULL,
  PRIMARY KEY (`adminId`, `commentaireId`),
  INDEX `fk_admin_has_commentaires_commentaires1_idx` (`commentaireId` ASC),
  INDEX `fk_admin_has_commentaires_admin1_idx` (`adminId` ASC),
  CONSTRAINT `fk_admin_has_commentaires_admin1`
    FOREIGN KEY (`adminId`)
    REFERENCES `Blog`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_has_commentaires_commentaires1`
    FOREIGN KEY (`commentaireId`)
    REFERENCES `Blog`.`commentaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`userReplyCommentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`userReplyCommentaire` (
  `userId` INT NOT NULL,
  `adminId` INT NOT NULL,
  `commentaireId` INT NOT NULL,
  `content` LONGTEXT NULL,
  `dateReply` DATETIME NULL,
  PRIMARY KEY (`userId`, `adminId`, `commentaireId`),
  INDEX `fk_user_has_adminReplyCommentaire_adminReplyCommentaire1_idx` (`adminId` ASC, `commentaireId` ASC),
  INDEX `fk_user_has_adminReplyCommentaire_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_user_has_adminReplyCommentaire_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `Blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_adminReplyCommentaire_adminReplyCommentaire1`
    FOREIGN KEY (`adminId` , `commentaireId`)
    REFERENCES `Blog`.`adminReplyCommentaire` (`adminId` , `commentaireId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
