<?php 
$this->title = 'Mon Blog : Liste des articles'; 
?>

<div class="articles">
	<?php foreach ($data as $key => $value){ 
		$overview = substr(strip_tags($data[$key]['content']),0, 100) . '...';
	?>
		<article class="multi">
		    <div class="title">
		    	<h1 class="titreBillet"><?= $data[$key]['title'] ?></h1>
		    	<time><em>Créer le : <?= $data[$key]['dateArticle'] ?></em></time>
		    </div>
		    <p><?= $overview ?></p>
		    <button><a href="<?php echo $this->app->getUrl('?controller=article&action=show&id=' . $data[$key]['id']);?>">Lire l'article</a></button>
		</article>
	<?php } ?>
</div>



