<?php 
$this->title = 'Mon Blog : ' . $data['article']['title']; 
?>

<article class="solo">
    <div class="title">
        <h1 class="titreBillet"><?= $data['article']['title'] ?></h1>
        <time><em>Créer le : <?= $data['article']['dateArticle'] ?></em></time>
    </div>
    <p><?= $data['article']['content'] ?></p>
    <button><a href="<?php echo $this->app->getUrl('?controller=article&action=index');?>">Retour à l'accueil</a></button>
</article>
<article class="comments">
	<fieldset>
		<legend>Vos commentaires</legend>
		<?php 
		foreach ($data['comments'] as $key => $value) {?>
			<div class="comment">
				<h4>Auteur : <?= $data['comments'][$key]['userPseudo'] ?></h4>
				<p><?= $data['comments'][$key]['content'] ?></p>
				<p><em>Posté le : <?= $data['comments'][$key]['dateComment'] ?></em></p>
				<form action="<?php echo $this->app->getUrl('?controller=comment&action=save');?>" method="post">
					<p><textarea name="content" id="mytextarea" placeholder="Votre commentaire" rows="5" required="required"></textarea></p>
					<input type="hidden" name="userId" value="1">
					<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
					<input type="hidden" name="articleId" value="<? echo $data['article']['id'] ?>">
					<input type="hidden" name="idParent" value="<? echo $data['comments'][$key]['id'] ?>">
					<input type="submit" value="Envoyer">
				</form>
				<?php if (isset($data['comments'][$key]['response'])) {
					foreach ($data['comments'][$key]['response'] as $comment => $com) {?>
						<div class="sousCommentaire" style="margin-left: 50px">
							<h4>Auteur : <?= $data['comments'][$key]['response'][$comment]['userPseudo'] ?></h4>
							<p><?= $data['comments'][$key]['response'][$comment]['content'] ?></p>
							<p><em>Posté le : <?= $data['comments'][$key]['response'][$comment]['dateComment'] ?></em></p>
						</div>
				<?php }}  ?>
			</div>	
		<?php }?>
		<form action="<?php echo $this->app->getUrl('?controller=comment&action=save');?>" method="post">
			<p><textarea name="content" id="mytextarea" placeholder="Votre commentaire" rows="5" required="required"></textarea></p>
			<input type="hidden" name="userId" value="1">
			<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
			<input type="hidden" name="articleId" value="<? echo $data['article']['id'] ?>">
			<input type="hidden" name="idParent" value="0">
			<input type="submit" value="Envoyer">
		</form>
	</fieldset>
</article>
