<?php 
$this->title = 'Interface de gestion des articles'; 
?>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h2 class="title">Liste de tous les articles</h2>
    <table class="table table-hover table-condensed table-responsive">
      <tr>
        <thead>
          <th>Titre</th>
          <th>Auteur</th>
          <th>Date Article</th>
          <th>Action</th>
        </thead>
      </tr>
      <?php foreach ($data as $key => $value){ ?>
      <tr>
        <tbody class="table-striped">
          <td><?= $data[$key]['title'] ?></td>
          <td><?= $data[$key]['adminPseudo'] ?></td>
          <td><?= $data[$key]['dateArticle'] ?></td>
          <td> 
              <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=record');?>"><button class="btn btn-default btn-xs">Nouvel Article</button></a>
             <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#modalArticle">Supprimer</button>
              <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=record&id=' . $data[$key]['id']);?>"><button class="btn btn-default btn-xs">Modifier</button></a>
              <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=show&id=' . $data[$key]['id']);?>"><button class="btn btn-default btn-xs">Vue</button></a>     
          </td>
        </tbody>
      </tr>
      <?php } ?>
    </table>
    <!-- Modal -->
    <div class="modal fade" id="modalArticle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body">
           <div class="alert alert-danger">       
               <i class="icon icon-times-circle icon-lg"></i>
               <strong>Attention !</strong><p>Êtes-vous sûr de vouloir supprimer cet article ?</p>
           </div> 
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=delete&id=' . $data[$key]['id']);?>"><button class="btn btn-danger" data-toggle="modal" data-target="#myModal">Supprimer</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
