<?php 
if (!is_null($this->request->getParam('id'))) {
	$this->title = 'Modification d\'un article';
}else{
	$this->title = 'Création d\'un article';
}
?>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <form class="form-horizontal" id="formArticle" action="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=save');?>" method="post" enctype="multipart/form-data">
        <h2 class="title"><?php  if (!is_null($this->request->getParam('id'))) {echo 'Modifier un article';}else{echo 'Créer un article';}?></h2>
        <div class="form-group">
          <label class="control-label col-sm-3" for="title">Titre de l'article : </label>
          <div class="col-sm-9">
            <input class="form-control" type="text" name="title" id="title" placeholder="Titre de l'article" value="<?php  if (!is_null($this->request->getParam('id'))) {echo $data['article']['title'];}?>">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3" for="imageArticle">Ajouter une image</label>
          <div class="col-sm-9">
              <input type="file" id="imageArticle" name="imageArticle">
          </div>
        </div>
        <p><label class="control-label" for="content">Contenu de votre article : </label></p>
        <p><textarea class="form-control" name="content" id="tinyMCE1" placeholder="Contenu de votre article" rows="20" cols="100"><?php  if (!is_null($this->request->getParam('id'))) {echo $data['article']['content'];}?></textarea></p>
        <input type="hidden" name="adminId" value="<? echo $_SESSION['adminId'] ?>">
        <input type="hidden" name="id" value="<?php  if (!is_null($this->request->getParam('id'))) {echo $data['article']['id'];}?>">
        <input type="hidden" name="dateArticle" value="<?echo date("Y-m-d H:i:s");?>">
        <button class="btn btn-default btn-sm" type="submit">Envoyer</button>
    </form>
    <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=index');?>"><button class="btn btn-danger btn-sm">Annuler</button></a>
  </div>
</div>
